'use client';

import { useState } from 'react';

interface Props {
  files: Record<string, string>;
  defaultName?: string;
  onClose: () => void;
}

export function ExportGitHubModal({ files, defaultName = 'omnidev-app', onClose }: Props) {
  const [repoName, setRepoName] = useState(defaultName);
  const [token, setToken] = useState('');
  const [isPrivate, setIsPrivate] = useState(false);
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  const [resultUrl, setResultUrl] = useState('');
  const [error, setError] = useState('');

  async function handleExport() {
    if (!repoName.trim() || !token.trim()) return;
    setStatus('loading');
    setError('');
    try {
      const res = await fetch('/api/export/github', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          files,
          repoName: repoName.trim(),
          token: token.trim(),
          private: isPrivate,
          description: 'Generated by OmniDev',
        }),
      });
      const data = await res.json();
      if (!res.ok || data.error) {
        setError(data.error || 'Export failed');
        setStatus('error');
        return;
      }
      setResultUrl(data.url);
      setStatus('success');
    } catch (err: any) {
      setError(err.message);
      setStatus('error');
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
      <div className="w-full max-w-md rounded-2xl bg-zinc-900 border border-zinc-700 p-6">
        <div className="flex items-center justify-between mb-5">
          <h2 className="text-lg font-semibold">Экспорт в GitHub</h2>
          <button onClick={onClose} className="text-zinc-500 hover:text-zinc-300 text-xl leading-none">×</button>
        </div>

        {status === 'success' ? (
          <div className="text-center py-4">
            <p className="text-green-400 mb-3">✓ Репозиторий создан</p>
            <a href={resultUrl} target="_blank" rel="noreferrer" className="text-violet-400 hover:underline break-all text-sm">{resultUrl}</a>
            <button onClick={onClose} className="mt-6 w-full py-2.5 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-sm">Закрыть</button>
          </div>
        ) : (
          <>
            <label className="block text-xs text-zinc-500 mb-1">Имя репозитория</label>
            <input value={repoName} onChange={(e) => setRepoName(e.target.value)}
              className="w-full bg-zinc-950 border border-zinc-700 rounded-xl px-4 py-2.5 text-sm mb-4 focus:outline-none focus:ring-2 focus:ring-violet-500" placeholder="my-awesome-app" />

            <label className="block text-xs text-zinc-500 mb-1">GitHub Personal Access Token</label>
            <input type="password" value={token} onChange={(e) => setToken(e.target.value)}
              className="w-full bg-zinc-950 border border-zinc-700 rounded-xl px-4 py-2.5 text-sm mb-2 focus:outline-none focus:ring-2 focus:ring-violet-500" placeholder="ghp_..." />
            <p className="text-[11px] text-zinc-600 mb-4">
              Нужны права <code className="text-zinc-400">repo</code>.{' '}
              <a href="https://github.com/settings/tokens/new?scopes=repo" target="_blank" rel="noreferrer" className="text-violet-400 hover:underline">Создать token</a>
            </p>

            <label className="flex items-center gap-2 text-sm text-zinc-400 mb-6 cursor-pointer">
              <input type="checkbox" checked={isPrivate} onChange={(e) => setIsPrivate(e.target.checked)} className="rounded" />
              Приватный репозиторий
            </label>

            {error && <p className="text-red-400 text-xs mb-3">{error}</p>}

            <button onClick={handleExport} disabled={status === 'loading' || !repoName.trim() || !token.trim()}
              className="w-full py-3 rounded-xl bg-violet-600 hover:bg-violet-500 disabled:opacity-40 text-sm font-medium">
              {status === 'loading' ? 'Создаю репозиторий...' : 'Экспортировать'}
            </button>
          </>
        )}
      </div>
    </div>
  );
}
