import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { files, repoName, description = 'Generated by OmniDev', token, private: isPrivate = false } = body as {
      files: Record<string, string>;
      repoName: string;
      description?: string;
      token: string;
      private?: boolean;
    };

    if (!files || !repoName || !token) {
      return NextResponse.json({ error: 'files, repoName and token required' }, { status: 400 });
    }

    const userRes = await fetch('https://api.github.com/user', {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
    });

    if (!userRes.ok) {
      const t = await userRes.text();
      return NextResponse.json({ error: `GitHub auth failed: ${userRes.status} ${t}` }, { status: 401 });
    }

    const user = await userRes.json();
    const owner = user.login;

    const createRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      body: JSON.stringify({ name: repoName, description, private: isPrivate, auto_init: false }),
    });

    if (!createRes.ok && createRes.status !== 422) {
      const t = await createRes.text();
      return NextResponse.json({ error: `Create repo failed: ${createRes.status} ${t}` }, { status: createRes.status });
    }

    const results: { path: string; ok: boolean }[] = [];

    for (const [path, content] of Object.entries(files)) {
      const encoded = Buffer.from(content, 'utf-8').toString('base64');
      let sha: string | undefined;

      const getRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/contents/${path}`, {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
      });
      if (getRes.ok) {
        const existing = await getRes.json();
        sha = existing.sha;
      }

      const putRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/contents/${path}`, {
        method: 'PUT',
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github+json',
          'Content-Type': 'application/json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
        body: JSON.stringify({
          message: `feat: add ${path} via OmniDev`,
          content: encoded,
          ...(sha ? { sha } : {}),
        }),
      });

      results.push({ path, ok: putRes.ok });
    }

    const failed = results.filter((r) => !r.ok);
    const htmlUrl = `https://github.com/${owner}/${repoName}`;

    return NextResponse.json({
      success: failed.length === 0,
      url: htmlUrl,
      owner,
      repo: repoName,
      filesWritten: results.filter((r) => r.ok).length,
      filesFailed: failed.map((f) => f.path),
    });
  } catch (err: any) {
    console.error('[export/github]', err);
    return NextResponse.json({ error: err.message || 'Export failed' }, { status: 500 });
  }
}
